### PR TITLE
Add whole mouse brain (00078)

### PR DESCRIPTION
**Pull request by mdw771**

### CODE REVIEW

**Comment by decarlof** [comment]
Please add in docs.data.tomosaic.rst:

- short description of the sample/experiment/motivation/challenge
- some details like how many filed of view were stitched, size of each fov, 
- add any info in docs.data.tomosaic.rst not in the file name (I renamed fulldata_flatcorr_1x.h5 to tomo_00078.h5)
- correct reference to image at line 10 of docs.data.tomosaic.rst 
       .. image:: ../img/tomo_00078.png ==> .. |00078| image:: ../img/tomo_00078.png

- add link to tomobank:
.. _tomo_00078: https://www.globus.org/app/transfer?origin_id=e133a81a-6d04-11e5-ba46-22000b92c6ec&origin_path=%2Ftomobank%2F%2Ftomo_00078%2F

- add link to tomosaic docs/repo
- generate a valid reconstructed slice with  
         python demo/tomopy_rec.py tomo_00078.h5 
specifying the correct --axis value to use and add the command in docs.data.tomosaic.rst
- add a description of the center_pos.txt and shifts.txt files.
 
Also consider adding the raw (multiple FOV) as collected and the tomosaic command the created the stiched file.

**Comment by mdw771** [comment]
Changed data description to charcoal and revised according to the previous comment

**Comment by decarlof** [comment]
@mdw771 I am accepting it as is and propose some changes on a new pull request

**Comment by decarlof** [comment]
@mdw771 here is how the new [page](https://tomobank.readthedocs.io/en/latest/source/data/docs.data.tomosaic.html#activated-charcoal) looks like.
Please send me the reference once the paper is accepted and I will add it in the [reference](https://tomobank.readthedocs.io/en/latest/source/credits.html#references) page

**Comment by mdw771** [comment]
Will do, thanks!

**Pull request merged**
